### ISSUE TITLE
Wrong namespace in provider

### ISSUE THREAD

**Issue by fnocetti** [nahid/imapx#3]
Hi! I had a lot of trouble when trying to publish the config and I figure out that it was due to an mistake in the service provider namespace.
You have 

`<?php

namespace Nahid\Imapx;

use Illuminate\Support\ServiceProvider;

class ImapxServiceProvider extends ServiceProvider`

and it should be

`<?php

namespace Nahidz\Imapx;

use Illuminate\Support\ServiceProvider;

class ImapxServiceProvider extends ServiceProvider`

Could you fix it?

**Comment by nahid** [comment]
Thank you @fnocetti for finding out this issue. Its now fixed.
Just enjoy it :+1:
